CREATE DATABASE COLLEGEDATABASE;
USE COLLEGEDATABASE;
#DATA CLEANING 
#ATTENDANCE TABLE
SELECT COUNT(*) AS NULL_VALUES FROM ATTENDANCE WHERE ATTENDANCEID IS NULL OR
                              STUDENTID IS NULL OR
                              COURSEID IS NULL OR
                              DATE IS NULL OR
                              ATTENDANCESTATUS IS NULL;
#COURSES TABLE
SELECT COUNT(*) AS NULL_VALUES FROM COURSES WHERE COURSEID IS NULL OR
                              COURSENAME IS NULL OR
                              DEPARTMENT IS NULL OR
                              CREDITS IS NULL OR
                              INSTRUCTOR IS NULL;
#ENROLLMENTS TABLE
SELECT COUNT(*) AS NULL_VALUES FROM ENROLLMENTS WHERE ENROLLMENTID IS NULL OR
                              STUDENTID IS NULL OR
                              COURSEID IS NULL OR
                              SEMESTER IS NULL OR
                               YEAR IS NULL OR
                              GRADE IS NULL;
#FEEDBACK TABLE
SELECT COUNT(*) AS NULL_VALUES FROM FEEDBACK WHERE FEEDBACKID IS NULL OR
                              STUDENTID IS NULL OR
                              FEEDBACKDATE IS NULL OR
                              FEEDBACKTEXT IS NULL;
#GRADES TABLE
SELECT COUNT(*) AS NULL_VALUES FROM GRADES WHERE GRADEID IS NULL OR
                              STUDENTID IS NULL OR
                              COURSEID IS NULL OR
                              DATE IS NULL OR
                              ASSIGNMENTTYPE IS NULL OR 
                              SCORE IS NULL;
#STUDENTS TABLE
SELECT COUNT(*) AS NULL_VALUES FROM STUDENTS WHERE FIRSTNAME IS NULL OR
                              STUDENTID IS NULL OR
                              LASTNAME IS NULL OR
                              GENDER IS NULL OR
                              DATEOFBIRTH IS NULL OR
                              MAJOR IS NULL OR
                              GPA IS NULL;
#COLUMN WISE NULL VALUES
SELECT SUM(CASE WHEN STUDENTID IS NULL THEN 1 ELSE 0 END) AS STUDENTID,
       SUM(CASE WHEN FIRSTNAME IS NULL THEN 1 ELSE 0 END) AS FIRSTNAME,
       SUM(CASE WHEN LASTNAME IS NULL THEN 1 ELSE 0 END) AS LASTNAME,
	   SUM(CASE WHEN GENDER IS NULL THEN 1 ELSE 0 END) AS GENDER,
	   SUM(CASE WHEN DATEOFBIRTH IS NULL THEN 1 ELSE 0 END) AS DATEOFBIRTH,
	   SUM(CASE WHEN MAJOR IS NULL THEN 1 ELSE 0 END) AS MAJOR,
	   SUM(CASE WHEN GPA IS NULL THEN 1 ELSE 0 END) AS GPA FROM STUDENTS;
#CHECKING DUPLICATE VALUES IN TABLES
SELECT STUDENTID,COUNT(*) AS DUPLICATES FROM STUDENTS
GROUP BY STUDENTID 
HAVING COUNT(*)>1;

SELECT ENROLLMENTID,COUNT(*) AS DUPLICATES FROM ENROLLMENTS
GROUP BY ENROLLMENTID 
HAVING COUNT(*)>1;

SELECT COURSEID,COUNT(*) AS DUPLICATES FROM COURSES
GROUP BY COURSEID 
HAVING COUNT(*)>1;
#CHECKING DATATYPE IN TABLE
DESC ATTENDANCE;
SET SQL_SAFE_UPDATE=0;
UPDATE ATTENDANCE
SET DATE=STR_TO_DATE(DATE,'%Y-%M-%D');
ALTER TABLE ATTENDANCE MODIFY COLUMN DATE DATE;

DESC COURSES;

DESC ENROLLMENTS;
ALTER TABLE ENROLLMENTS MODIFY COLUMN YEAR YEAR;
DESC FEEDBACK;
       
 #List all students with their full name, gender, major, and GPA
 SELECT CONCAT(FIRSTNAME," ",LASTNAME) AS FULLNAME,GENDER,MAJOR,GPA FROM STUDENTS;
 #Show the attendance records for a given student on a particular date
 SELECT *FROM ATTENDANCE WHERE STUDENTID=1086 AND DATE='2022/06/07';
 #List all enrollment records for the current year
 SELECT *FROM ENROLLMENTS WHERE YEAR=2024;
 #Display all feedback submitted, ordered from newest to oldest
 SELECT *FROM FEEDBACK ORDER BY FEEDBACKDATE DESC LIMIT 15;
 #Show each student's enrolled courses (Student Full Name + Course Name + Semester + Year).
SELECT A.SEMESTER,
	   A.YEAR,
       A.STUDENTID,
       CONCAT(B.FIRSTNAME," ",B.LASTNAME) AS FULLNAME,
       C.COURSENAME,
       E.ASSIGNMENTTYPE
FROM ENROLLMENTS AS A JOIN STUDENTS AS B ON A.STUDENTID=B.STUDENTID 
JOIN COURSES AS C ON A.COURSEID=C.COURSEID
JOIN ATTENDANCE AS D ON A.STUDENTID=D.STUDENTID
JOIN GRADES AS E ON A.STUDENTID=E.STUDENTID;
CREATE VIEW JOINTABLE AS (SELECT A.SEMESTER,
	   A.YEAR,
       A.STUDENTID,
       CONCAT(B.FIRSTNAME," ",B.LASTNAME) AS FULLNAME,
       C.COURSENAME,
       E.ASSIGNMENTTYPE
FROM ENROLLMENTS AS A JOIN STUDENTS AS B ON A.STUDENTID=B.STUDENTID 
JOIN COURSES AS C ON A.COURSEID=C.COURSEID
JOIN ATTENDANCE AS D ON A.STUDENTID=D.STUDENTID
JOIN GRADES AS E ON A.STUDENTID=E.STUDENTID);

#Count how many students are enrolled in each course
SELECT COUNT(STUDENTID) AS TOTAL_STUDENTS,COURSENAME FROM JOINTABLE 
GROUP BY COURSENAME;
#Find the average grade score for each course 
SELECT AVG(SCORE) AS AVG_SCORE,COURSEID FROM GRADES 
GROUP BY COURSEID 
ORDER BY AVG(SCORE) DESC LIMIT 10;
#Calculate the attendance percentage for each student in each course.
SELECT StudentID, CourseID,(SUM(CASE WHEN AttendanceStatus='Present' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS AttendancePercentage
FROM ATTENDANCE
GROUP BY StudentID, CourseID;
#Identify students with attendance below 75% in any course.
SELECT STUDENTID,COURSEID,(SUM(CASE WHEN AttendanceStatus='Present' THEN 1 ELSE 0 END) / COUNT(*)) * 100 AS AttendancePercentage 
FROM ATTENDANCE  
GROUP BY COURSEID,STUDENTID
HAVING ATTENDANCEPERCENTAGE<90;
#Determine the most popular course (highest enrollment count).
SELECT COURSEID,COUNT(ENROLLMENTID) AS HIGH_COUNT 
FROM ENROLLMENTS
GROUP BY COURSEID 
ORDER BY HIGH_COUNT DESC LIMIT 1;
#Find students who are taking more than 3 courses in the same semester.
SELECT STUDENTID,COUNT(COURSEID),SEMESTER,YEAR FROM ENROLLMENTS 
GROUP BY STUDENTID,SEMESTER,YEAR
HAVING COUNT(COURSEID)>0;
#List students who scored the highest Score in each course for a specific assignment type.
SELECT AssignmentType, CourseID, StudentID, Score 
FROM (SELECT AssignmentType,CourseID,StudentID,Score,ROW_NUMBER() OVER (PARTITION BY AssignmentType ORDER BY Score DESC) AS rn
    FROM GRADES
) AS ranked
WHERE rn = 1;

